### ISSUE TITLE
[BUG] The basic skincrate will continue to allow you to open it even after you have all the skins

### ISSUE THREAD

**Issue by AwesomeNess26108** [paradoxum-games/bugs#88] opened 2022-03-02 05:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have a basic skincrate and all of the skins obtainable from it (like I do), you can still open it and the "you can't open this yet" message will not appear. This just wastes money as you are getting a skin you already have, and duplicate skins don't exist.

### Expected Behavior

The "you can't open this yet" message should appear if you try to open the basic skincrate after having obtained all skins.

### Steps To Reproduce

1. Join the main lobby
2. Make sure you have every basic crate skin obtained
3. Obtain a basic skincrate
4. Open the skincrate
5. The "you can't open this yet" message will not stop you and you waste a skincrate

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/emdSF0DuNaM Video

**Comment by PhoenixShay** [comment] 2022-03-02 12:32
Dupe of #77

**Closed by PhoenixShay** 2022-03-02 12:32 UTC
Labels: triage
