### ISSUE TITLE
Unable to sell Military Bases in the Halloween event.

### ISSUE THREAD

**Issue by ShinyGemm** [paradoxum-games/bugs#24] opened 2020-11-12 22:18 UTC
**Describe the bug** — *a clear and concise description of what the bug is!*
Currently, in the new event, as what has been reported to me by members in my discord, you cannot sell Military Bases.

**To Reproduce** — *steps to reproduce the behavior!*
1. Equip the Military Base.
2. Join a Halloween game.
3. Place down a Military Base.
4. Attempt to sell.

**Expected behavior** — *a clear and concise description of what you expected to happen!*
The military base should be removed, along with refunding the cash spent on it.
**Screenshots** — *if applicable, add screenshots to help explain your problem.*
https://cdn.discordapp.com/attachments/756338951140147200/773218334291787786/Roblox_2020-11-03_11-12-23.mp4

**Comment by Razuatix** [comment] 2020-11-12 22:19
This issue is a duplicate of #5

It does not sell in any mode, including events.

**Closed by Razuatix** 2020-11-12 22:19 UTC
Labels: tower-defense-simulator
