### ISSUE TITLE
[BUG] Equipping skins on towers cause massive lag spikes

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#82] opened 2022-03-02 01:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Similar to Eggrypted's report, when you select any skin on any tower the game lags both in FPS and ping. When spam selected, the game lags heavily. 

### Expected Behavior

Be able to select a skin without any FPS drops or ping spikes. 

### Steps To Reproduce

1. Join the main lobby
2. Go to inventory
3. Select a tower
4. Change the tower's skins

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [X] Phone

### Additional Information

You can see my FPS in the top left, and my ping in the top right.

https://user-images.githubusercontent.com/100169010/156276849-e3e5854b-efe1-4a6b-b749-81c03e9e72c8.mp4

![image](https://user-images.githubusercontent.com/100169010/156276957-a283a6ef-939a-40ec-b6cb-ded1c39ad23a.png)

**Comment by PhoenixShay** [comment] 2022-03-02 01:38
Duplicate of #73

**Closed by PhoenixShay** 2022-03-02 01:38 UTC
Labels: duplicate
