### ISSUE TITLE
Equipping any tower skin causes major lag/fps drops

### ISSUE THREAD

**Issue by BiscuitCat** [paradoxum-games/bugs#94] opened 2022-03-02 19:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Equipping a skin from your inventory causes lag spikes and massive lag drops if you spam it

### Expected Behavior

Transition from equipping skins should remain smooth without the game lagging and fps dropping 

### Steps To Reproduce

1. Join the main lobby
2. Go to inventory
3. Click a tower skin to equip/spam click equip

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video showing the fps drops
https://gyazo.com/c51e36602d75a0fac19f545d18ca0fff

**Comment by PhoenixShay** [comment] 2022-03-02 19:44
Dupe of #82

**Closed by PhoenixShay** 2022-03-02 19:44 UTC
Labels: duplicate
